{
  "sudo": "false",
  "language": "java",
  "jdk": "openjdk8",      #though my version says 1.8, that means version 8 update 1

  "install": "true",

  "script": [
  "./mvnw clean install"
  ],
  "group": "stable",
  "os": "linux"
}
